spring:
    application:
        name: user-center
    datasource:
        url: jdbc:mysql://localhost:3306/yupi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
    session:
        # session超时时间，1天
        timeout: 86400
server:
    port: 8080
mybatis-plus:
    global-config:
        db-config:
            logic-delete-field: isDeleted # 全局逻辑删除字段名
            logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
            logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0

