spring:
    application:
        name: user-center
    datasource:
        url: jdbc:mysql://localhost:3306/yupi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
server:
    port: 8080

